using System.Windows.Input;

namespace CapYap.Utils.Windows
{
    public static class InputUtils
    {
        private static readonly Dictionary<SharpDX.DirectInput.Key, Key> keyMap =
            new()
            {
            { SharpDX.DirectInput.Key.Unknown, Key.None },
            { SharpDX.DirectInput.Key.Escape, Key.Escape },
            { SharpDX.DirectInput.Key.D1, Key.D1 },
            { SharpDX.DirectInput.Key.D2, Key.D2 },
            { SharpDX.DirectInput.Key.D3, Key.D3 },
            { SharpDX.DirectInput.Key.D4, Key.D4 },
            { SharpDX.DirectInput.Key.D5, Key.D5 },
            { SharpDX.DirectInput.Key.D6, Key.D6 },
            { SharpDX.DirectInput.Key.D7, Key.D7 },
            { SharpDX.DirectInput.Key.D8, Key.D8 },
            { SharpDX.DirectInput.Key.D9, Key.D9 },
            { SharpDX.DirectInput.Key.D0, Key.D0 },
            { SharpDX.DirectInput.Key.Minus, Key.OemMinus },
            { SharpDX.DirectInput.Key.Equals, Key.OemPlus },
            { SharpDX.DirectInput.Key.Back, Key.Back },
            { SharpDX.DirectInput.Key.Tab, Key.Tab },
            { SharpDX.DirectInput.Key.Q, Key.Q },
            { SharpDX.DirectInput.Key.W, Key.W },
            { SharpDX.DirectInput.Key.E, Key.E },
            { SharpDX.DirectInput.Key.R, Key.R },
            { SharpDX.DirectInput.Key.T, Key.T },
            { SharpDX.DirectInput.Key.Y, Key.Y },
            { SharpDX.DirectInput.Key.U, Key.U },
            { SharpDX.DirectInput.Key.I, Key.I },
            { SharpDX.DirectInput.Key.O, Key.O },
            { SharpDX.DirectInput.Key.P, Key.P },
            { SharpDX.DirectInput.Key.LeftBracket, Key.OemOpenBrackets },
            { SharpDX.DirectInput.Key.RightBracket, Key.OemCloseBrackets },
            { SharpDX.DirectInput.Key.Return, Key.Enter },
            { SharpDX.DirectInput.Key.LeftControl, Key.LeftCtrl },
            { SharpDX.DirectInput.Key.A, Key.A },
            { SharpDX.DirectInput.Key.S, Key.S },
            { SharpDX.DirectInput.Key.D, Key.D },
            { SharpDX.DirectInput.Key.F, Key.F },
            { SharpDX.DirectInput.Key.G, Key.G },
            { SharpDX.DirectInput.Key.H, Key.H },
            { SharpDX.DirectInput.Key.J, Key.J },
            { SharpDX.DirectInput.Key.K, Key.K },
            { SharpDX.DirectInput.Key.L, Key.L },
            { SharpDX.DirectInput.Key.Semicolon, Key.OemSemicolon },
            { SharpDX.DirectInput.Key.Apostrophe, Key.OemQuotes },
            { SharpDX.DirectInput.Key.Grave, Key.OemTilde },
            { SharpDX.DirectInput.Key.LeftShift, Key.LeftShift },
            { SharpDX.DirectInput.Key.Backslash, Key.OemBackslash },
            { SharpDX.DirectInput.Key.Z, Key.Z },
            { SharpDX.DirectInput.Key.X, Key.X },
            { SharpDX.DirectInput.Key.C, Key.C },
            { SharpDX.DirectInput.Key.V, Key.V },
            { SharpDX.DirectInput.Key.B, Key.B },
            { SharpDX.DirectInput.Key.N, Key.N },
            { SharpDX.DirectInput.Key.M, Key.M },
            { SharpDX.DirectInput.Key.Comma, Key.OemComma },
            { SharpDX.DirectInput.Key.Period, Key.OemPeriod },
            { SharpDX.DirectInput.Key.Slash, Key.Oem2 },
            { SharpDX.DirectInput.Key.RightShift, Key.RightShift },
            { SharpDX.DirectInput.Key.Multiply, Key.Multiply },
            { SharpDX.DirectInput.Key.LeftAlt, Key.LeftAlt },
            { SharpDX.DirectInput.Key.Space, Key.Space },
            { SharpDX.DirectInput.Key.Capital, Key.CapsLock },
            { SharpDX.DirectInput.Key.F1, Key.F1 },
            { SharpDX.DirectInput.Key.F2, Key.F2 },
            { SharpDX.DirectInput.Key.F3, Key.F3 },
            { SharpDX.DirectInput.Key.F4, Key.F4 },
            { SharpDX.DirectInput.Key.F5, Key.F5 },
            { SharpDX.DirectInput.Key.F6, Key.F6 },
            { SharpDX.DirectInput.Key.F7, Key.F7 },
            { SharpDX.DirectInput.Key.F8, Key.F8 },
            { SharpDX.DirectInput.Key.F9, Key.F9 },
            { SharpDX.DirectInput.Key.F10, Key.F10 },
            { SharpDX.DirectInput.Key.NumberLock, Key.NumLock },
            { SharpDX.DirectInput.Key.ScrollLock, Key.Scroll },
            { SharpDX.DirectInput.Key.NumberPad7, Key.NumPad7 },
            { SharpDX.DirectInput.Key.NumberPad8, Key.NumPad8 },
            { SharpDX.DirectInput.Key.NumberPad9, Key.NumPad9 },
            { SharpDX.DirectInput.Key.Subtract, Key.Subtract },
            { SharpDX.DirectInput.Key.NumberPad4, Key.NumPad4 },
            { SharpDX.DirectInput.Key.NumberPad5, Key.NumPad5 },
            { SharpDX.DirectInput.Key.NumberPad6, Key.NumPad6 },
            { SharpDX.DirectInput.Key.Add, Key.Add },
            { SharpDX.DirectInput.Key.NumberPad1, Key.NumPad1 },
            { SharpDX.DirectInput.Key.NumberPad2, Key.NumPad2 },
            { SharpDX.DirectInput.Key.NumberPad3, Key.NumPad3 },
            { SharpDX.DirectInput.Key.NumberPad0, Key.NumPad0 },
            { SharpDX.DirectInput.Key.Decimal, Key.Decimal },
            { SharpDX.DirectInput.Key.Oem102, Key.OemBackslash },
            { SharpDX.DirectInput.Key.F11, Key.F11 },
            { SharpDX.DirectInput.Key.F12, Key.F12 },
            { SharpDX.DirectInput.Key.F13, Key.F13 },
            { SharpDX.DirectInput.Key.F14, Key.F14 },
            { SharpDX.DirectInput.Key.F15, Key.F15 },
            { SharpDX.DirectInput.Key.Kana, Key.KanaMode },
            { SharpDX.DirectInput.Key.AbntC1, Key.AbntC1 },
            { SharpDX.DirectInput.Key.Convert, Key.ImeConvert },
            { SharpDX.DirectInput.Key.NoConvert, Key.ImeNonConvert },
            { SharpDX.DirectInput.Key.Yen, Key.OemBackslash },
            { SharpDX.DirectInput.Key.AbntC2, Key.AbntC2 },
            { SharpDX.DirectInput.Key.NumberPadEquals, Key.OemPlus },
            { SharpDX.DirectInput.Key.PreviousTrack, Key.MediaPreviousTrack },
            { SharpDX.DirectInput.Key.AT, Key.None },
            { SharpDX.DirectInput.Key.Colon, Key.OemSemicolon },
            { SharpDX.DirectInput.Key.Underline, Key.OemMinus },
            { SharpDX.DirectInput.Key.Kanji, Key.KanjiMode },
            { SharpDX.DirectInput.Key.Stop, Key.MediaStop },
            { SharpDX.DirectInput.Key.AX, Key.None },
            { SharpDX.DirectInput.Key.Unlabeled, Key.None },
            { SharpDX.DirectInput.Key.NextTrack, Key.MediaNextTrack },
            { SharpDX.DirectInput.Key.NumberPadEnter, Key.Enter },
            { SharpDX.DirectInput.Key.RightControl, Key.RightCtrl },
            { SharpDX.DirectInput.Key.Mute, Key.VolumeMute },
            { SharpDX.DirectInput.Key.Calculator, Key.LaunchApplication1 },
            { SharpDX.DirectInput.Key.PlayPause, Key.MediaPlayPause },
            { SharpDX.DirectInput.Key.MediaStop, Key.MediaStop },
            { SharpDX.DirectInput.Key.VolumeDown, Key.VolumeDown },
            { SharpDX.DirectInput.Key.VolumeUp, Key.VolumeUp },
            { SharpDX.DirectInput.Key.WebHome, Key.BrowserHome },
            { SharpDX.DirectInput.Key.NumberPadComma, Key.Separator },
            { SharpDX.DirectInput.Key.Divide, Key.Divide },
            { SharpDX.DirectInput.Key.PrintScreen, Key.PrintScreen },
            { SharpDX.DirectInput.Key.RightAlt, Key.RightAlt },
            { SharpDX.DirectInput.Key.Pause, Key.Pause },
            { SharpDX.DirectInput.Key.Home, Key.Home },
            { SharpDX.DirectInput.Key.Up, Key.Up },
            { SharpDX.DirectInput.Key.PageUp, Key.PageUp },
            { SharpDX.DirectInput.Key.Left, Key.Left },
            { SharpDX.DirectInput.Key.Right, Key.Right },
            { SharpDX.DirectInput.Key.End, Key.End },
            { SharpDX.DirectInput.Key.Down, Key.Down },
            { SharpDX.DirectInput.Key.PageDown, Key.PageDown },
            { SharpDX.DirectInput.Key.Insert, Key.Insert },
            { SharpDX.DirectInput.Key.Delete, Key.Delete },
            { SharpDX.DirectInput.Key.LeftWindowsKey, Key.LWin },
            { SharpDX.DirectInput.Key.RightWindowsKey, Key.RWin },
            { SharpDX.DirectInput.Key.Applications, Key.Apps },
            { SharpDX.DirectInput.Key.Power, Key.Sleep },
            { SharpDX.DirectInput.Key.Sleep, Key.Sleep },
            { SharpDX.DirectInput.Key.Wake, Key.None },
            { SharpDX.DirectInput.Key.WebSearch, Key.BrowserSearch },
            { SharpDX.DirectInput.Key.WebFavorites, Key.BrowserFavorites },
            { SharpDX.DirectInput.Key.WebRefresh, Key.BrowserRefresh },
            { SharpDX.DirectInput.Key.WebStop, Key.BrowserStop },
            { SharpDX.DirectInput.Key.WebForward, Key.BrowserForward },
            { SharpDX.DirectInput.Key.WebBack, Key.BrowserBack },
            { SharpDX.DirectInput.Key.MyComputer, Key.LaunchApplication2 },
            { SharpDX.DirectInput.Key.Mail, Key.LaunchMail },
            { SharpDX.DirectInput.Key.MediaSelect, Key.SelectMedia }
            };

        public static Key ToWpfKey(SharpDX.DirectInput.Key sharpDxKey)
        {
            if (keyMap.TryGetValue(sharpDxKey, out Key wpfKey))
                return wpfKey;

            return Key.None;
        }
    }
}
