name: .NET

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Set version number
      id: version
      shell: bash
      run: |
        VERSION=$(date +"%y.%m.%d.%H%M")
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Version: $VERSION"

    - name: Create version branch
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git checkout -b ${{ env.VERSION }}
        git push origin ${{ env.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish
      run: dotnet publish --configuration Release

    - name: Install NSIS
      run: choco install nsis -y

    - name: Build NSIS installer
      run: |
        call post_build.bat Assets\icon.ico $(OutDir) NSIS\Installer.nsi ${{ env.VERSION }}
      shell: cmd

    - name: Find installer
      id: find_installer
      shell: bash
      run: |
        INSTALLER=$(find . -name "*.exe" | grep -i installer | head -n 1)
        echo "INSTALLER=$INSTALLER" >> $GITHUB_ENV
        echo "Found installer: $INSTALLER"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION }}
        name: Release ${{ env.VERSION }}
        files: ${{ env.INSTALLER }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
